### ISSUE TITLE
Change Item Template error Unicorn thrown exception

### ISSUE THREAD

**Issue by longvh92** [SitecoreUnicorn/Unicorn#268]
I got an error when changing item template. It happens on every template in my Sitecore instance, whenever I make a change, after the Next button in **change template Popup**, it shows the blank popup but my expectation is a popup with success text. See image below
The info popup show we change item template
![image](https://user-images.githubusercontent.com/22469529/34429825-3ae7e398-ec90-11e7-9d73-8ecdf5445be9.png)
After clicking the Next button
![image](https://user-images.githubusercontent.com/22469529/34428911-1376b426-ec84-11e7-987f-ffc8f2de8baf.png)
Totally blank.
And Sitecore logs has thrown an exception:

> Exception: System.NullReferenceException
Message: Object reference not set to an instance of an object.
Source: Unicorn
   at Unicorn.Data.DataProvider.UnicornDataProvider.ChangeTemplate(ItemDefinition itemDefinition, TemplateChangeList changeList, CallContext context)
   at Unicorn.Data.DataProvider.UnicornSqlServerDataProvider.ChangeTemplate(ItemDefinition itemDefinition, TemplateChangeList changeList, CallContext context)
   at Sitecore.Data.DataProviders.DataProvider.ChangeTemplate(ItemDefinition item, TemplateChangeList changes, CallContext context, DataProviderCollection providers)
   at Sitecore.Data.Managers.TemplateManager.ChangeTemplate(Item item, TemplateChangeList changes)
   at Sitecore.Data.Items.Item.ChangeTemplate(TemplateItem template)
   at Sitecore.Shell.Applications.Templates.ChangeTemplate.ChangeTemplateForm.ChangeTemplate()
   at Sitecore.Shell.Applications.Templates.ChangeTemplate.ChangeTemplateForm.ActivePageChanged(String page, String oldPage)
   at Sitecore.Web.UI.Pages.WizardForm.set_Active(String value)
   at Sitecore.Web.UI.HtmlControls.Button.DoClick(Message message)

Iam using Sitecore 8.0 Update 3 and the latest 4.3 Unicorn version.

Please help,
Thanks.

**Comment by longvh92** [comment]
For more information, I am using transparent sync to restore content item and template from existing SQL Database, then put it into source control so we I setup the instance everywhere without restore database.

**Comment by cassidydotdk** [comment]
Can you share the YML for the template, item and standard values in question please?
