### ISSUE TITLE
Rapid item creation sometimes fails with file locks

### ISSUE THREAD

**Issue by cassidydotdk** [SitecoreUnicorn/Unicorn#302]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A few reports have come in. Like this one from @Kasaku

> Exception: System.IO.IOException
> Message: The process cannot access the file 'C:\...\Presentation\Rendering Variants\JSON List\Default\Title.yml' because it is being used by another process.

**If the current behavior is a bug, please provide the steps to reproduce.**
That's the problem. Seems related to rapid item generation. Like running scripts, creating branch templates.

**What is the expected behavior?**
No file lock errors

**Please mention your Sitecore version and Unicorn version.**
Reported on 4.0.3

**Comment by cassidydotdk** [comment]
Another log exerpt

> ManagedPoolThread #8 15:55:26 INFO  [Unicorn]: Serialization File System Data Store: Serialized /sitecore/content/Client/Base Site/Presentation/Rendering Variants/Search Box/vertical/Title (9de2be70-1abe-49e8-9d80-75e2f1eca3ca) to disk (Version Added).
> ManagedPoolThread #8 15:55:26 INFO  [Unicorn]: Serialization File System Data Store: Serialized /sitecore/content/Client/Base Site/Presentation/Rendering Variants/Search Box/vertical/Title (9de2be70-1abe-49e8-9d80-75e2f1eca3ca) to disk (Version Added).
> ManagedPoolThread #8 15:55:26 ERROR Failed to save the item. Item ID: {9DE2BE70-1ABE-49E8-9D80-75E2F1ECA3CA}, database: master
> Exception: System.IO.IOException
> Message: The process cannot access the file 'C:\source\Client\src\Project\Client\serialization\Content\Base Site\Presentation\Rendering Variants\Search Box\vertical\Title.yml' because it is being used by another process.
> Source: mscorlib
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.InternalDelete(String path, Boolean checkHost)
>    at Rainbow.Storage.SerializationFileSystemTree.WriteItem(IItemData item, String path)
>    at Rainbow.Storage.SerializationFileSystemTree.Save(IItemData item)
>    at Unicorn.Data.DataProvider.UnicornDataProvider.SaveItem(ItemDefinition itemDefinition, ItemChanges changes, CallContext context)
>    at Unicorn.Data.DataProvider.UnicornSqlServerDataProvider.SaveItem(ItemDefinition itemDefinition, ItemChanges changes, CallContext context)
>    at Sitecore.Data.DataProviders.DataProvider.SaveItem(ItemDefinition item, ItemChanges changes, CallContext context, DataProviderCollection providers)
>    at Sitecore.Data.DataSource.SaveItem(ID itemID, ItemChanges changes)
>    at Sitecore.Data.Engines.EngineCommand`2.Execute()
>    at Sitecore.Data.Engines.DataEngine.SaveItem(Item item)
> 
> ManagedPoolThread #8 15:55:26 ERROR Failed to add the item version. Item ID: {9DE2BE70-1ABE-49E8-9D80-75E2F1ECA3CA}, database: master, language: fr-FR
> Exception: System.IO.IOException
> Message: The process cannot access the file 'C:\source\Client\src\Project\Client\serialization\Content\Base Site\Presentation\Rendering Variants\Search Box\vertical\Title.yml' because it is being used by another process.
> Source: mscorlib
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.File.InternalDelete(String path, Boolean checkHost)
>    at Rainbow.Storage.SerializationFileSystemTree.WriteItem(IItemData item, String path)
>    at Rainbow.Storage.SerializationFileSystemTree.Save(IItemData item)
>    at Unicorn.Data.DataProvider.UnicornDataProvider.SaveItem(ItemDefinition itemDefinition, ItemChanges changes, CallContext context)
>    at Unicorn.Data.DataProvider.UnicornSqlServerDataProvider.SaveItem(ItemDefinition itemDefinition, ItemChanges changes, CallContext context)
>    at Sitecore.Data.DataProviders.DataProvider.SaveItem(ItemDefinition item, ItemChanges changes, CallContext context, DataProviderCollection providers)
>    at Sitecore.Data.DataSource.SaveItem(ID itemID, ItemChanges changes)
>    at Sitecore.Data.Engines.EngineCommand`2.Execute()
>    at Sitecore.Data.Engines.DataEngine.SaveItem(Item item)
>    at Sitecore.Pipelines.ItemProvider.SaveItem.TriggerDataEngine.Process(SaveItemArgs args)
>    at (Object , Object[] )
>    at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
>    at Sitecore.Data.Managers.DefaultItemManager.SaveItem(Item item)
>    at Sitecore.Nexus.Data.DataCommands.AddVersionCommand.Execute(Item item)
>    at Sitecore.Data.Engines.EngineCommand`2.Execute()
>    at Sitecore.Data.Engines.DataEngine.AddVersion(Item item)
> 
>

**Comment by cassidydotdk** [comment]
Verify this on 4.0.6
