### ISSUE TITLE
Unicorn Sync fails halfway through a long-running operation after users are synced

### ISSUE THREAD

**Issue by DThrasher** [SitecoreUnicorn/Unicorn#342]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

A Unicorn sync operation, using the Unicorn.psm1 PowerShell module, fails after 10-15 minutes, usually during or after attempting to synchronize users. The Sitecore instance we are syncing with has the Active Directory module enabled, and we suspect this might have something to do with the long delay after user sync and eventual error.

We are able to sync Sitecore interactively using the Unicorn.aspx file, but not from our Azure DevOps PowerShell script.

On the Azure DevOps server, the error message is something like:
Exception calling "ReadLine" with "0" argument(s): "Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."

The error message we get in the Sitecore logs is the following:

> 6260 16:43:40 INFO  [Unicorn]: Something.Project.Storefront.Users user sync complete.
6260 16:43:40 INFO  [Unicorn]: Something.Project.Storefront is being synced with Dilithium SQL enabled.
6260 16:43:40 ERROR ERROR: The remote host closed the connection. The error code is 0x800704CD. (System.Web.HttpException)
at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async)
   at System.Web.HttpWriter.Write(String s)
   at System.Web.HttpResponseWrapper.Write(String s)
   at Kamsar.WebConsole.TextWebConsole.Write(String statusMessage, MessageType type, Object[] formatParameters)
   at Unicorn.Logging.PubSubLogger.Flush()
   at Unicorn.SerializationHelper.SyncConfigurations(IConfiguration[] configurations, IProgressStatus progress, ILogger additionalLogger)

> 6260 16:43:40 INFO  [Unicorn] Dilithium SQL context has been released.
6260 16:43:40 INFO  [Unicorn] Dilithium Rainbow context has been released.
6260 16:43:40 ERROR Application error.
Exception: System.Web.HttpException
Message: The remote host closed the connection. The error code is 0x800704CD.
Source: System.Web
   at System.Web.Hosting.IIS7WorkerRequest.RaiseCommunicationError(Int32 result, Boolean throwOnDisconnect)
   at System.Web.Hosting.IIS7WorkerRequest.ExplicitFlush()
   at System.Web.HttpResponse.Flush(Boolean finalFlush, Boolean async)
   at System.Web.HttpWriter.Write(String s)
   at System.Web.HttpResponseWrapper.Write(String s)
   at Kamsar.WebConsole.TextWebConsole.Write(String statusMessage, MessageType type, Object[] formatParameters)
   at Kamsar.WebConsole.WebConsole.WriteException(Exception exception)
   at Unicorn.ControlPanel.Responses.WebConsoleResponse.Execute(HttpResponseBase response)
   at Unicorn.ControlPanel.UnicornControlPanelPipelineProcessor.ProcessRequest(HttpContext context)
   at Unicorn.ControlPanel.UnicornControlPanelPipelineProcessor.Process(HttpRequestArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.Nexus.Web.HttpModule.(Object , EventArgs )
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**If the current behavior is a bug, please provide the steps to reproduce.**
We can reproduce this consistently in one of our 13 Sitecore environments, but the others work fine. We suspect that Sitecore configuration, IIS configuration, or possibly server resources may be causing this issue.

**What is the expected behavior?**
Syncing through the PowerShell module, Unicorn.psm1, would work just like syncing interactively through Unicorn.aspx

**Please mention your Sitecore version and Unicorn version.**
Sitecore 8.2 Update-3 with Unicorn 4.0.3

**Comment by kamsar** [comment]
It sounds like a firewall or load balancer might be terminating http connections after a period of time. Especially with it being only one environment. Definitely looks network level to me.
________________________________

**Comment by DThrasher** [comment]
The error seems pretty low-level to me as well -- definitely smells like a network issue or timeout. But the PowerShell module is invoked using the VSTS agent on the CM server itself, and the URL is in our hosts file on the CM server. My assumption is that we're not going outside the box -- unless what we're seeing is an issue with Sitecore communicating with my client's LDAP.

**Comment by cassidydotdk** [comment]
Would have to speculate this is an issue with the solution, not the product itself. Client LDAP would be a prime suspect.
