### ISSUE TITLE
Sitecore 10.1 uses Sitecore.Kernel 16.0.0.0 version which does not have attribute 'UsedImplicitlyAttribute'  and unicorn uses this attribute

### ISSUE THREAD

**Issue by SudhirKumar2254** [SitecoreUnicorn/Unicorn#416]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
I was trying to use copy site function in Sitecore.Demo.Platform demo and faced this error.

**What is the expected behavior?**
It should not throw any error
**Please mention your Sitecore version and Unicorn version.**
Sitecore version 10.1 and unicorn 4.1.4

**Comment by SudhirKumar2254** [comment]
I am getting below error.

1616 14:39:17 INFO   Script/Library saved '/sitecore/system/Modules/PowerShell/Script Library/SXA/SXA - Multisite/Functions/Site cloning' by user 'sitecore\Admin'
2624 14:39:46 ERROR Error while loading commands from assembly  Unicorn list: Could not load type 'Sitecore.UsedImplicitlyAttribute' from assembly 'Sitecore.Kernel, Version=16.0.0.0, Culture=neutral, PublicKeyToken=null'.
Exception: System.TypeLoadException
Message: Could not load type 'Sitecore.UsedImplicitlyAttribute' from assembly 'Sitecore.Kernel, Version=16.0.0.0, Culture=neutral, PublicKeyToken=null'.
Source: mscorlib
   at System.ModuleHandle.ResolveType(RuntimeModule module, Int32 typeToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount, ObjectHandleOnStack type)
   at System.ModuleHandle.ResolveTypeHandleInternal(RuntimeModule module, Int32 typeToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.RuntimeModule.ResolveType(Int32 metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at Spe.Core.Host.SpeSitecorePowerShellSnapIn.Ge

**Comment by cassidydotdk** [comment]
I've pushed https://github.com/SitecoreUnicorn/Unicorn/releases/tag/4.1.6-pre2 that should fix it. Please install this version and confirm, thanks :)

**Comment by SudhirKumar2254** [comment]
This fix worked. Not able to see this error anymore. Thanks @cassidydotdk
